# Generated by Django 4.0.4 on 2024-04-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img1', models.ImageField(upload_to='item_images/')),
                ('img2', models.ImageField(upload_to='item_images/')),
                ('img3', models.ImageField(upload_to='item_images/')),
                ('location', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('daley_name', models.CharField(max_length=100)),
                ('daley_number', models.CharField(max_length=15)),
                ('daley_image', models.ImageField(upload_to='daley_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Usermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('confirmpassword', models.CharField(max_length=100)),
            ],
        ),
    ]
